### ISSUE TITLE
Question re: syntax

### ISSUE THREAD

**Issue by adamwooding** [carolineschnapp/shipping-calculator#16]
Hi @carolineschnapp ,

I hope you don't mind me asking this question. I noticed that in the shipping-calculator.liquid file, you have used these opening and closing tags `<%  %>`. I can't seem to find any reference to the use of those tags. Can you please let me know what they do?

Thank you so much,
Adam Wooding

**Comment by illarionvk** [comment]
`<% %>` tag syntax is a part of [Underscore.js/Lodash templates](http://underscorejs.org/#template).

Shipping calculator uses the Underscore.js template to render itself on the page.

**Comment by adamwooding** [comment]
Hi @illarionvk 

Thank you very much for your reply :)
